name: Descomprimir
on: [push]
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: unzip -o -q AntiExtravio*.zip || unzip -o -q *.zip || ls -la
      - run: |
          rm -f *.zip
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add -A
          git commit -m "descomprimido" || echo "ya esta"
          git push
